### ISSUE TITLE
Shadow Demon talent and ability suggestions

### ISSUE THREAD

**Issue by dymil** [leamare/nerds-builds#23]
The ability leveling in the guide has the ultimate leveled up whenever it's available, but the description says not to do that.

The talent suggestions also need updating, as they refer to old talents which have since been rearranged.

**Comment by leamare** [comment]
Yeah, this build was initially based on a guide by slashstrike. Haven't been able to update it properly since then. Will look into it tomorrow (and merge the grammar changes).
